[project]
name = "slices"
version = "0.1.0"
description = "Structured Linear CDE (SLiCE) layers for sequence modelling"
authors = [
    {name = "Benjamin Walker",email = "mail@benwalker.co.uk"}
]
readme = "README.md"
requires-python = ">=3.10,<3.15"
packages = [{ include = "slices", from = "src" }]
dependencies = [
    "torch (>=2.9.1,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.14.13"
pre-commit = "^4.5.1"

